import _ from 'lodash';

function QuestionFactory(){

  let questions = [{question: "How many sharps in the key of C Major?", answers: [{answer: 0, correct: true},{answer: 1,correct: false},{answer: 2,correct: false},{answer: 3,correct: false}]},
    {question: "How many sharps in the key of G Major?", answers: [{answer: 1, correct: true},{answer: 0,correct: false},{answer: 2,correct: false},{answer: 3,correct: false}]},
    {question: "How many sharps in the key of D Major?", answers: [{answer: 2, correct: true},{answer: 0,correct: false},{answer: 1,correct: false},{answer: 3,correct: false}]},
    {question: "How many sharps in the key of A Major?", answers: [{answer: 3, correct: true},{answer: 1,correct: false},{answer: 2,correct: false},{answer: 4,correct: false}]},
    {question: "How many sharps in the key of E Major?", answers: [{answer: 4, correct: true},{answer: 2,correct: false},{answer: 3,correct: false},{answer: 5,correct: false}]},
    {question: "How many sharps in the key of B Major?", answers: [{answer: 5, correct: true},{answer: 3,correct: false},{answer: 4,correct: false},{answer: 6,correct: false}]},
    {question: "How many sharps in the key of F# Major?", answers: [{answer: 6, correct: true},{answer: 4,correct: false},{answer: 5,correct: false},{answer: 7,correct: false}]},
    {question: "How many sharps in the key of C# Major?", answers: [{answer: 7, correct: true},{answer: 4,correct: false},{answer: 5,correct: false},{answer: 6,correct: false}]},
    {question: "How many sharps in the key of A minor?", answers: [{answer: 0, correct: true},{answer: 1,correct: false},{answer: 2,correct: false},{answer: 3,correct: false}]},
    {question: "How many sharps in the key of E minor?", answers: [{answer: 1, correct: true},{answer: 0,correct: false},{answer: 2,correct: false},{answer: 3,correct: false}]},
    {question: "How many sharps in the key of B minor?", answers: [{answer: 2, correct: true},{answer: 0,correct: false},{answer: 1,correct: false},{answer: 3,correct: false}]},
    {question: "How many sharps in the key of F# minor?", answers: [{answer: 3, correct: true},{answer: 1,correct: false},{answer: 2,correct: false},{answer: 4,correct: false}]},
    {question: "How many sharps in the key of C# minor?", answers: [{answer: 4, correct: true},{answer: 2,correct: false},{answer: 3,correct: false},{answer: 5,correct: false}]},
    {question: "How many sharps in the key of G# minor?", answers: [{answer: 5, correct: true},{answer: 3,correct: false},{answer: 4,correct: false},{answer: 6,correct: false}]},
    {question: "How many flats in the key of F Major?", answers: [{answer: 1, correct: true},{answer: 2,correct: false},{answer: 3,correct: false},{answer: 4,correct: false}]},
    {question: "How many flats in the key of Bb Major?", answers: [{answer: 2, correct: true},{answer: 1,correct: false},{answer: 3,correct: false},{answer: 4,correct: false}]},
    {question: "How many flats in the key of Eb Major?", answers: [{answer: 3, correct: true},{answer: 2,correct: false},{answer: 4,correct: false},{answer: 5,correct: false}]},
    {question: "How many flats in the key of Ab Major?", answers: [{answer: 4, correct: true},{answer: 3,correct: false},{answer: 5,correct: false},{answer: 6,correct: false}]},
    {question: "How many flats in the key of Db Major?", answers: [{answer: 5, correct: true},{answer: 3,correct: false},{answer: 4,correct: false},{answer: 6,correct: false}]},
    {question: "How many flats in the key of Gb Major?", answers: [{answer: 6, correct: true},{answer: 4,correct: false},{answer: 5,correct: false},{answer: 7,correct: false}]},
    {question: "How many flats in the key of Cb Major?", answers: [{answer: 7, correct: true},{answer: 4,correct: false},{answer: 5,correct: false},{answer: 6,correct: false}]},
    {question: "How many flats in the key of D minor?", answers: [{answer: 1, correct: true},{answer: 2,correct: false},{answer: 3,correct: false},{answer: 4,correct: false}]},
    {question: "How many flats in the key of G minor?", answers: [{answer: 2, correct: true},{answer: 1,correct: false},{answer: 3,correct: false},{answer: 4,correct: false}]},
    {question: "How many flats in the key of C minor?", answers: [{answer: 3, correct: true},{answer: 2,correct: false},{answer: 4,correct: false},{answer: 5,correct: false}]},
    {question: "How many flats in the key of F minor?", answers: [{answer: 4, correct: true},{answer: 3,correct: false},{answer: 5,correct: false},{answer: 6,correct: false}]},
    {question: "How many flats in the key of Bb minor?", answers: [{answer: 5, correct: true},{answer: 3,correct: false},{answer: 4,correct: false},{answer: 6,correct: false}]},
    {question: "How many flats in the key of Eb minor?", answers: [{answer: 6, correct: true},{answer: 4,correct: false},{answer: 5,correct: false},{answer: 7,correct: false}]},
    {question: "What is the 1st Church Mode?", answers: [{answer: "Ionian", correct: true},{answer: "Dorian",correct: false},{answer: "Phrygian",correct: false},{answer: "Lydian",correct: false}]},
    {question: "What is the 2nd Church Mode?", answers: [{answer: "Dorian", correct: true},{answer: "Mixolydian",correct: false},{answer: "Phrygian",correct: false},{answer: "Lydian",correct: false}]},
    {question: "What is the 3rd Church Mode?", answers: [{answer: "Phrygian", correct: true},{answer: "Mixolydian",correct: false},{answer: "Ionian",correct: false},{answer: "Lydian",correct: false}]},
    {question: "What is the 4th Church Mode?", answers: [{answer: "Lydian", correct: true},{answer: "Mixolydian",correct: false},{answer: "Ionian",correct: false},{answer: "Dorian",correct: false}]},
    {question: "What is the 5th Church Mode?", answers: [{answer: "Mixolydian", correct: true},{answer: "Phrygian",correct: false},{answer: "Aeolian",correct: false},{answer: "Locrian",correct: false}]},
    {question: "What is the 6th Church Mode?", answers: [{answer: "Aeolian", correct: true},{answer: "Phrygian",correct: false},{answer: "Lydian",correct: false},{answer: "Locrian",correct: false}]},
    {question: "What is the 7th Church Mode?", answers: [{answer: "Locrian", correct: true},{answer: "Phrygian",correct: false},{answer: "Aeolian",correct: false},{answer: "Mixolydian",correct: false}]},
    {question: "What notes of the major scale make up a Major chord?", answers: [{answer: "1 3 5", correct: true},{answer: "1 2 3",correct: false},{answer: "1 3 4",correct: false},{answer: "1 b3 5",correct: false}]},
    {question: "What notes of the major scale make up a minor chord?", answers: [{answer: "1 b3 5", correct: true},{answer: "1 2 3",correct: false},{answer: "1 3 4",correct: false},{answer: "1 3 5",correct: false}]},
    {question: "What notes of the major scale make up a diminished chord?", answers: [{answer: "1 b3 b5", correct: true},{answer: "1 2 3",correct: false},{answer: "1 3 5",correct: false},{answer: "1 b3 5",correct: false}]},
    {question: "What notes of the major scale make up a augmented chord?", answers: [{answer: "1 3 #5", correct: true},{answer: "1 #3 5",correct: false},{answer: "1 3 5",correct: false},{answer: "1 b3 5",correct: false}]},
    {question: "What notes of the major scale make up a suspended chord?", answers: [{answer: "1 4 5", correct: true},{answer: "1 3 5",correct: false},{answer: "1 b3 5",correct: false},{answer: "1 5 6",correct: false}]},
    {question: "What notes of the major scale make up a 2 chord?", answers: [{answer: "1 2 5", correct: true},{answer: "1 3 5",correct: false},{answer: "1 2 3",correct: false},{answer: "1 2 4",correct: false}]},
    {question: "What notes of the major scale make up a 7 chord?", answers: [{answer: "1 3 5 b7", correct: true},{answer: "1 3 5 7",correct: false},{answer: "1 3 7 8",correct: false},{answer: "1 3 5 6",correct: false}]},
    {question: "What notes of the major scale make up a Maj7 chord?", answers: [{answer: "1 3 5 7", correct: true},{answer: "1 3 5 b7",correct: false},{answer: "1 2 3 4",correct: false},{answer: "1 3 7 9",correct: false}]},
    {question: "What notes of the major scale make up a min7 chord?", answers: [{answer: "1 b3 5 b7", correct: true},{answer: "1 3 5 b7",correct: false},{answer: "1 2 b3 4",correct: false},{answer: "1 b3 7 9",correct: false}]},
    {question: "What is the second chord in the key of C Major?", answers: [{answer: "Dmin", correct: true},{answer: "Amin",correct: false},{answer: "Gmin",correct: false},{answer: "Emin",correct: false}]},
    {question: "What is the second chord in the key of D Major?", answers: [{answer: "Emin", correct: true},{answer: "Cmin",correct: false},{answer: "F#min",correct: false},{answer: "Bmin",correct: false}]},
    {question: "What is the second chord in the key of A Major?", answers: [{answer: "Bmin", correct: true},{answer: "Cmin",correct: false},{answer: "Gmin",correct: false},{answer: "Dmin",correct: false}]},
    {question: "What is the second chord in the key of E Major?", answers: [{answer: "F#min", correct: true},{answer: "Amin",correct: false},{answer: "Bmin",correct: false},{answer: "Dmin",correct: false}]},
    {question: "What is the second chord in the key of B Major?", answers: [{answer: "C#min", correct: true},{answer: "D#",correct: false},{answer: "Emin",correct: false},{answer: "E",correct: false}]},
    {question: "What is the third chord in the key of C Major?", answers: [{answer: "Emin", correct: true},{answer: "Fmin",correct: false},{answer: "Gmin",correct: false},{answer: "Amin",correct: false}]},
    {question: "What is the third chord in the key of G Major?", answers: [{answer: "Bmin", correct: true},{answer: "Emin",correct: false},{answer: "Dmin",correct: false},{answer: "Amin",correct: false}]},
    {question: "What is the third chord in the key of A Major?", answers: [{answer: "C#min", correct: true},{answer: "Cmin",correct: false},{answer: "Gmin",correct: false},{answer: "Emin",correct: false}]},
    {question: "What is the third chord in the key of E Major?", answers: [{answer: "G#min", correct: true},{answer: "Gmin",correct: false},{answer: "Bmin",correct: false},{answer: "Amin",correct: false}]},
    {question: "What is the fourth chord in the key of C Major?", answers: [{answer: "F", correct: true},{answer: "G",correct: false},{answer: "E",correct: false},{answer: "A",correct: false}]},
    {question: "What is the fourth chord in the key of G Major?", answers: [{answer: "C", correct: true},{answer: "D",correct: false},{answer: "Emin",correct: false},{answer: "A",correct: false}]},
    {question: "What is the fourth chord in the key of A Major?", answers: [{answer: "D", correct: true},{answer: "E",correct: false},{answer: "F#",correct: false},{answer: "B",correct: false}]},
    {question: "What is the fifth chord in the key of C Major?", answers: [{answer: "G", correct: true},{answer: "E",correct: false},{answer: "F",correct: false},{answer: "A",correct: false}]},
    {question: "What is the fifth chord in the key of G Major?", answers: [{answer: "D", correct: true},{answer: "A",correct: false},{answer: "E",correct: false},{answer: "C",correct: false}]},
    {question: "What is the fifth chord in the key of D Major?", answers: [{answer: "A", correct: true},{answer: "G",correct: false},{answer: "E",correct: false},{answer: "C",correct: false}]},
    {question: "What is the fifth chord in the key of A Major?", answers: [{answer: "E", correct: true},{answer: "G",correct: false},{answer: "D",correct: false},{answer: "F#",correct: false}]},
    {question: "What is the fifth chord in the key of B Major?", answers: [{answer: "F#", correct: true},{answer: "A",correct: false},{answer: "E",correct: false},{answer: "D#",correct: false}]},
    {question: "What is the fifth chord in the key of F Major?", answers: [{answer: "C", correct: true},{answer: "Bb",correct: false},{answer: "D",correct: false},{answer: "A",correct: false}]},
    {question: "What is the fifth chord in the key of Bb Major?", answers: [{answer: "F", correct: true},{answer: "Eb",correct: false},{answer: "E",correct: false},{answer: "C",correct: false}]},
    {question: "What is relative minor of C Major?", answers: [{answer: "Amin", correct: true},{answer: "Bmin",correct: false},{answer: "Emin",correct: false},{answer: "Fmin",correct: false}]},
    {question: "What is relative minor of G Major?", answers: [{answer: "Emin", correct: true},{answer: "Bmin",correct: false},{answer: "Amin",correct: false},{answer: "Fmin",correct: false}]},
    {question: "What is relative minor of D Major?", answers: [{answer: "Bmin", correct: true},{answer: "Amin",correct: false},{answer: "Emin",correct: false},{answer: "Fmin",correct: false}]},
    {question: "What is relative minor of A Major?", answers: [{answer: "F#min", correct: true},{answer: "Bmin",correct: false},{answer: "Emin",correct: false},{answer: "C#min",correct: false}]},
    {question: "What is relative minor of E Major?", answers: [{answer: "C#min", correct: true},{answer: "Bmin",correct: false},{answer: "F#min",correct: false},{answer: "G#min",correct: false}]},
    {question: "What is relative minor of B Major?", answers: [{answer: "G#min", correct: true},{answer: "Emin",correct: false},{answer: "F#min",correct: false},{answer: "Amin",correct: false}]},
    {question: "What is relative minor of E Major?", answers: [{answer: "C#min", correct: true},{answer: "Bmin",correct: false},{answer: "F#min",correct: false},{answer: "G#min",correct: false}]},
    {question: "What is relative minor of F# Major?", answers: [{answer: "D#min", correct: true},{answer: "Bmin",correct: false},{answer: "C#min",correct: false},{answer: "G#min",correct: false}]},
    {question: "What is relative minor of C# Major?", answers: [{answer: "A#min", correct: true},{answer: "D#min",correct: false},{answer: "F#min",correct: false},{answer: "G#min",correct: false}]},
    {question: "What is relative minor of F Major?", answers: [{answer: "Dmin", correct: true},{answer: "Bmin",correct: false},{answer: "Gmin",correct: false},{answer: "Amin",correct: false}]},
    {question: "What is relative minor of Bb Major?", answers: [{answer: "Gmin", correct: true},{answer: "Bmin",correct: false},{answer: "Cmin",correct: false},{answer: "Amin",correct: false}]},
    {question: "What is relative minor of Eb Major?", answers: [{answer: "Cmin", correct: true},{answer: "Fmin",correct: false},{answer: "Gmin",correct: false},{answer: "Amin",correct: false}]},
    {question: "What is relative minor of Ab Major?", answers: [{answer: "Fmin", correct: true},{answer: "Bbmin",correct: false},{answer: "Gmin",correct: false},{answer: "Amin",correct: false}]},
    {question: "What is relative minor of Db Major?", answers: [{answer: "Bbmin", correct: true},{answer: "Fmin",correct: false},{answer: "Gmin",correct: false},{answer: "Ebmin",correct: false}]},
    {question: "What is relative minor of Gb Major?", answers: [{answer: "Ebmin", correct: true},{answer: "Fmin",correct: false},{answer: "Gmin",correct: false},{answer: "Abmin",correct: false}]},
    {question: "What is relative minor of Cb Major?", answers: [{answer: "Abmin", correct: true},{answer: "Dbmin",correct: false},{answer: "Ebmin",correct: false},{answer: "Amin",correct: false}]}];

  return {
    getQuestion: getQuestion
  }

  function getQuestion(category){
    let arrLength = questions.length;
    let rand = _.random(0, arrLength);
    return questions[rand];
  }
}

export { QuestionFactory }